import { readFile } from 'node:fs/promises';
const checks=[];const ok=(name,cond)=>{if(!cond)throw new Error(`FAIL: ${name}`);checks.push(name)};
const read=p=>readFile(new URL(`../${p}`,import.meta.url),'utf8');
const r2=await read('src/lib/r2-publish-source.server.ts');
const upload=await read('src/lib/youtube-upload.functions.ts');
const pub=await read('src/lib/youtube-publisher-v2.server.ts');
const render=await read('src/lib/render-pipeline.server.ts');
const sched=await read('src/lib/campaign-scheduler.server.ts');
const migration=await read('supabase/migrations/20260907140000_phase8_r2_direct_publisher_fleet.sql');
const worker=await read('worker/src/index.mjs');
ok('range reads from R2',/Range:`bytes=\$\{start\}-\$\{endInclusive\}`/.test(r2));
ok('publisher never requires whole R2 MP4',/uploadResumableR2Object/.test(upload)&&/readR2Range/.test(upload));
ok('worker exposes R2 object identity',/outputObjectKey:j\.output_object_key/.test(worker));
ok('render finalization persists object key',/finalizeR2Render/.test(render)&&/render_output_object_key/.test(render));
ok('scheduler uses advisory leader RPC',/phase8_dispatch_campaign_scheduler/.test(sched)&&/pg_try_advisory_xact_lock/.test(migration));
ok('publisher fleet table exists',/CREATE TABLE IF NOT EXISTS public\.publisher_nodes/.test(migration));
ok('multi-publisher claims remain skip-locked',/FOR UPDATE SKIP LOCKED/.test(await read('supabase/migrations/20260907130000_phase7_exactly_once_publishing.sql')));
ok('crash checkpoint source verified',/source_verified/.test(upload));
ok('crash checkpoint session created',/youtube_session_created/.test(upload));
ok('crash checkpoint upload progress',/upload_progress/.test(upload));
ok('crash checkpoint youtube committed',/youtube_committed/.test(upload));
ok('crash checkpoint campaign committed',/campaign_committed/.test(upload));
ok('fault injection persists after durable checkpoint',/PUBLISH_CRASH_AFTER_CHECKPOINT/.test(pub)&&/external_commit_checkpoint/.test(pub));
ok('R2-ready dispatch no longer needs Supabase copy',/render_output_object_key IS NOT NULL OR ci\.rendered_video_url IS NOT NULL/.test(migration));
console.log(`Phase 8 certification passed: ${checks.length}/${checks.length}`);for(const c of checks)console.log(`  ✓ ${c}`);
