import { readFile } from 'node:fs/promises';
const read=p=>readFile(new URL(`../${p}`,import.meta.url),'utf8');
const checks=[];const ok=(n,c)=>{if(!c)throw new Error(`FAIL: ${n}`);checks.push(n)};
const migration=await read('supabase/migrations/20260907160000_phase9_deployment_control_plane.sql');
const control=await read('src/lib/deployment-control-plane.server.ts');
const render=await read('src/lib/render-pipeline.server.ts');
const pub=await read('src/lib/youtube-publisher-v2.server.ts');
const pubRoute=await read('src/routes/api/public/hooks/process-publisher.ts');
const schedRoute=await read('src/routes/api/public/hooks/process-scheduler.ts');
const ops=await read('src/routes/_app/operations.tsx');
const keda=await read('deploy/phase9/keda.yaml');
const deploy=await read('deploy/phase9/kubernetes.yaml');
const workflow=await read('.github/workflows/production-release.yml');
ok('control-plane settings table',/CREATE TABLE IF NOT EXISTS public\.control_plane_settings/.test(migration));
ok('render autoscale recommendation',/render_target_queued_per_replica/.test(migration)&&/desiredReplicas/.test(control));
ok('publisher autoscale recommendation',/publisher_target_queued_per_replica/.test(migration));
ok('render hard admission ceiling',/render_max_queued/.test(migration)&&/render admission paused/.test(render));
ok('publisher and scheduler have separate endpoints',/processPublishQueue/.test(pubRoute)&&/dispatchUpcomingCampaignItems/.test(schedRoute));
ok('publisher fleet remains skip-locked',/claim_publish_jobs/.test(pub)&&/FOR UPDATE SKIP LOCKED/.test(migration));
ok('post-YouTube-commit jobs remain reclaimable',/CREATE OR REPLACE FUNCTION public\.claim_publish_jobs/.test(migration)&&!/youtube_video_id IS NULL[\s\S]*ORDER BY pj.next_attempt_at/.test(migration.split('crash-drill repair')[1]||''));
ok('fault injection is staging-gated',/ALLOW_PUBLISH_FAULT_INJECTION/.test(pub)&&/faultCampaignItemId/.test(pub));
ok('combined operations dashboard',/Render fleet/.test(ops)&&/Publisher fleet/.test(ops)&&/Production certification/.test(ops));
ok('KEDA render queue scaler',/name: shorts-renderers/.test(keda)&&/render_queue_jobs/.test(keda));
ok('KEDA publisher queue scaler',/name: shorts-publishers/.test(keda)&&/publish_jobs/.test(keda));
ok('independent renderer publisher scheduler deployments',/name: shorts-renderer/.test(deploy)&&/name: shorts-publisher/.test(deploy)&&/name: shorts-scheduler/.test(deploy));
ok('production release hard-gates live certification',/phase9-live-certify\.mjs/.test(workflow)&&/environment: production/.test(workflow));
console.log(`Phase 9 certification passed: ${checks.length}/${checks.length}`);for(const c of checks)console.log(`  ✓ ${c}`);
