import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'); const checks=[]; const ok=(name,cond)=>{checks.push([name,!!cond]);};
const sql=read('supabase/migrations/20260907213000_phase11_saas_billing_entitlements.sql');
const billing=read('src/lib/billing.server.ts'); const fn=read('src/lib/billing.functions.ts'); const gov=read('src/lib/tenant-governance.server.ts'); const render=read('src/lib/render-pipeline.server.ts'); const webhook=read('src/routes/api/public/billing/webhook.ts'); const page=read('src/routes/_app/billing.tsx'); const ops=read('src/routes/_app/operations.tsx'); const tree=read('src/routeTree.gen.ts');
ok('billing plan catalog',/billing_plans/.test(sql)&&/starter/.test(sql)&&/business/.test(sql));
ok('subscription truth',/tenant_subscriptions/.test(sql)&&/current_period_end/.test(sql)&&/grace_until/.test(sql));
ok('entitlement resolver syncs phase10',/phase11_sync_entitlements/.test(sql)&&/tenant_capacity_policies/.test(sql));
ok('admin overrides',/entitlement_overrides/.test(sql)&&/setEntitlementOverride/.test(fn));
ok('invoice and credit tracking',/billing_invoices/.test(sql)&&/billing_credit_ledger/.test(sql));
ok('webhook replay protection',/billing_webhook_events/.test(sql)&&/23505/.test(billing));
ok('stripe signature verification',/stripe-signature/.test(webhook)&&/createHmac/.test(billing)&&/timingSafeEqual/.test(billing));
ok('checkout and portal',/checkout\/sessions/.test(billing)&&/billing_portal\/sessions/.test(billing));
ok('grace and cancel entitlement semantics',/past_due/.test(sql)&&/cancel_at_period_end/.test(sql)&&/BILLING_GRACE_HOURS/.test(billing));
ok('overage opt-in and cap',/tenant_billing_preferences/.test(sql)&&/billing_overage_charges/.test(sql)&&/phase11_authorize_render_overage/.test(gov));
ok('render overage idempotency reference',/assertRenderGovernance\((?:row.user_id|governance.subjectUserId), estimatedCost, row.id\)/.test(render));
ok('tenant usage billing page',/Plans & Billing/.test(page)&&/Usage/.test(page)&&/Invoices/.test(page));
ok('billing operations metrics',/Billing & entitlements/.test(ops)&&/Pending overage/.test(ops));
ok('billing routes registered',/\/_app\/billing/.test(tree)&&/api\/public\/billing\/webhook/.test(tree));
for(const [n,v] of checks) console.log(`${v?'PASS':'FAIL'} ${n}`); const failed=checks.filter(x=>!x[1]); console.log(`\n${checks.length-failed.length}/${checks.length} checks passed`); if(failed.length) process.exit(1);
