/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYoutubeConnectRouteImport } from './routes/_app/youtube-connect'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppDataStudioRouteImport } from './routes/_app/data-studio'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns/index'
import { Route as AppTemplatesNewRouteImport } from './routes/_app/templates/new'
import { Route as AppEditorTemplateIdRouteImport } from './routes/_app/editor/$templateId'
import { Route as AppCampaignsNewRouteImport } from './routes/_app/campaigns/new'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/_app/campaigns/$campaignId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube/callback'
import { Route as ApiPublicHooksRenderCallbackRouteImport } from './routes/api/public/hooks/render-callback'
import { Route as ApiPublicHooksProcessCampaignQueueRouteImport } from './routes/api/public/hooks/process-campaign-queue'
import { Route as AppCampaignsCampaignIdTestRenderRouteImport } from './routes/_app/campaigns/$campaignId.test-render'
import { Route as AppCampaignsCampaignIdQueueRouteImport } from './routes/_app/campaigns/$campaignId.queue'
import { Route as AppCampaignsCampaignIdCalendarRouteImport } from './routes/_app/campaigns/$campaignId.calendar'
import { Route as AppCampaignsCampaignIdAutomationRouteImport } from './routes/_app/campaigns/$campaignId.automation'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYoutubeConnectRoute = AppYoutubeConnectRouteImport.update({
  id: '/youtube-connect',
  path: '/youtube-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppDataStudioRoute = AppDataStudioRouteImport.update({
  id: '/data-studio',
  path: '/data-studio',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorTemplateIdRoute = AppEditorTemplateIdRouteImport.update({
  id: '/editor/$templateId',
  path: '/editor/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRenderCallbackRoute =
  ApiPublicHooksRenderCallbackRouteImport.update({
    id: '/api/public/hooks/render-callback',
    path: '/api/public/hooks/render-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessCampaignQueueRoute =
  ApiPublicHooksProcessCampaignQueueRouteImport.update({
    id: '/api/public/hooks/process-campaign-queue',
    path: '/api/public/hooks/process-campaign-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCampaignsCampaignIdTestRenderRoute =
  AppCampaignsCampaignIdTestRenderRouteImport.update({
    id: '/test-render',
    path: '/test-render',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdQueueRoute =
  AppCampaignsCampaignIdQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdCalendarRoute =
  AppCampaignsCampaignIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)
const AppCampaignsCampaignIdAutomationRoute =
  AppCampaignsCampaignIdAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AppCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assets': typeof AppAssetsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/data-studio': typeof AppDataStudioRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/youtube-connect': typeof AppYoutubeConnectRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/editor/$templateId': typeof AppEditorTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/campaigns/$campaignId/automation': typeof AppCampaignsCampaignIdAutomationRoute
  '/campaigns/$campaignId/queue': typeof AppCampaignsCampaignIdQueueRoute
  '/campaigns/$campaignId/calendar': typeof AppCampaignsCampaignIdCalendarRoute
  '/campaigns/$campaignId/test-render': typeof AppCampaignsCampaignIdTestRenderRoute
  '/api/public/hooks/process-campaign-queue': typeof ApiPublicHooksProcessCampaignQueueRoute
  '/api/public/hooks/render-callback': typeof ApiPublicHooksRenderCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assets': typeof AppAssetsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/data-studio': typeof AppDataStudioRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/youtube-connect': typeof AppYoutubeConnectRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/editor/$templateId': typeof AppEditorTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/campaigns/$campaignId/automation': typeof AppCampaignsCampaignIdAutomationRoute
  '/campaigns/$campaignId/queue': typeof AppCampaignsCampaignIdQueueRoute
  '/campaigns/$campaignId/calendar': typeof AppCampaignsCampaignIdCalendarRoute
  '/campaigns/$campaignId/test-render': typeof AppCampaignsCampaignIdTestRenderRoute
  '/api/public/hooks/process-campaign-queue': typeof ApiPublicHooksProcessCampaignQueueRoute
  '/api/public/hooks/render-callback': typeof ApiPublicHooksRenderCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/data-studio': typeof AppDataStudioRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/youtube-connect': typeof AppYoutubeConnectRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRouteWithChildren
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/editor/$templateId': typeof AppEditorTemplateIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/campaigns/$campaignId/automation': typeof AppCampaignsCampaignIdAutomationRoute
  '/_app/campaigns/$campaignId/queue': typeof AppCampaignsCampaignIdQueueRoute
  '/_app/campaigns/$campaignId/calendar': typeof AppCampaignsCampaignIdCalendarRoute
  '/_app/campaigns/$campaignId/test-render': typeof AppCampaignsCampaignIdTestRenderRoute
  '/api/public/hooks/process-campaign-queue': typeof ApiPublicHooksProcessCampaignQueueRoute
  '/api/public/hooks/render-callback': typeof ApiPublicHooksRenderCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assets'
    | '/analytics'
    | '/data-studio'
    | '/dashboard'
    | '/settings'
    | '/youtube-connect'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/editor/$templateId'
    | '/templates/new'
    | '/campaigns/'
    | '/templates/'
    | '/campaigns/$campaignId/automation'
    | '/campaigns/$campaignId/queue'
    | '/campaigns/$campaignId/calendar'
    | '/campaigns/$campaignId/test-render'
    | '/api/public/hooks/process-campaign-queue'
    | '/api/public/hooks/render-callback'
    | '/api/public/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assets'
    | '/analytics'
    | '/data-studio'
    | '/dashboard'
    | '/settings'
    | '/youtube-connect'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/editor/$templateId'
    | '/templates/new'
    | '/campaigns'
    | '/templates'
    | '/campaigns/$campaignId/automation'
    | '/campaigns/$campaignId/queue'
    | '/campaigns/$campaignId/calendar'
    | '/campaigns/$campaignId/test-render'
    | '/api/public/hooks/process-campaign-queue'
    | '/api/public/hooks/render-callback'
    | '/api/public/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/assets'
    | '/_app/analytics'
    | '/_app/data-studio'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/youtube-connect'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/campaigns/$campaignId'
    | '/_app/campaigns/new'
    | '/_app/editor/$templateId'
    | '/_app/templates/new'
    | '/_app/campaigns/'
    | '/_app/templates/'
    | '/_app/campaigns/$campaignId/automation'
    | '/_app/campaigns/$campaignId/queue'
    | '/_app/campaigns/$campaignId/calendar'
    | '/_app/campaigns/$campaignId/test-render'
    | '/api/public/hooks/process-campaign-queue'
    | '/api/public/hooks/render-callback'
    | '/api/public/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksProcessCampaignQueueRoute: typeof ApiPublicHooksProcessCampaignQueueRoute
  ApiPublicHooksRenderCallbackRoute: typeof ApiPublicHooksRenderCallbackRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/youtube-connect': {
      id: '/_app/youtube-connect'
      path: '/youtube-connect'
      fullPath: '/youtube-connect'
      preLoaderRoute: typeof AppYoutubeConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-studio': {
      id: '/_app/data-studio'
      path: '/data-studio'
      fullPath: '/data-studio'
      preLoaderRoute: typeof AppDataStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor/$templateId': {
      id: '/_app/editor/$templateId'
      path: '/editor/$templateId'
      fullPath: '/editor/$templateId'
      preLoaderRoute: typeof AppEditorTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$campaignId': {
      id: '/_app/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/render-callback': {
      id: '/api/public/hooks/render-callback'
      path: '/api/public/hooks/render-callback'
      fullPath: '/api/public/hooks/render-callback'
      preLoaderRoute: typeof ApiPublicHooksRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-campaign-queue': {
      id: '/api/public/hooks/process-campaign-queue'
      path: '/api/public/hooks/process-campaign-queue'
      fullPath: '/api/public/hooks/process-campaign-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessCampaignQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/campaigns/$campaignId/test-render': {
      id: '/_app/campaigns/$campaignId/test-render'
      path: '/test-render'
      fullPath: '/campaigns/$campaignId/test-render'
      preLoaderRoute: typeof AppCampaignsCampaignIdTestRenderRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/queue': {
      id: '/_app/campaigns/$campaignId/queue'
      path: '/queue'
      fullPath: '/campaigns/$campaignId/queue'
      preLoaderRoute: typeof AppCampaignsCampaignIdQueueRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/calendar': {
      id: '/_app/campaigns/$campaignId/calendar'
      path: '/calendar'
      fullPath: '/campaigns/$campaignId/calendar'
      preLoaderRoute: typeof AppCampaignsCampaignIdCalendarRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
    '/_app/campaigns/$campaignId/automation': {
      id: '/_app/campaigns/$campaignId/automation'
      path: '/automation'
      fullPath: '/campaigns/$campaignId/automation'
      preLoaderRoute: typeof AppCampaignsCampaignIdAutomationRouteImport
      parentRoute: typeof AppCampaignsCampaignIdRoute
    }
  }
}

interface AppCampaignsCampaignIdRouteChildren {
  AppCampaignsCampaignIdAutomationRoute: typeof AppCampaignsCampaignIdAutomationRoute
  AppCampaignsCampaignIdQueueRoute: typeof AppCampaignsCampaignIdQueueRoute
  AppCampaignsCampaignIdCalendarRoute: typeof AppCampaignsCampaignIdCalendarRoute
  AppCampaignsCampaignIdTestRenderRoute: typeof AppCampaignsCampaignIdTestRenderRoute
}

const AppCampaignsCampaignIdRouteChildren: AppCampaignsCampaignIdRouteChildren =
  {
    AppCampaignsCampaignIdAutomationRoute:
      AppCampaignsCampaignIdAutomationRoute,
    AppCampaignsCampaignIdQueueRoute: AppCampaignsCampaignIdQueueRoute,
    AppCampaignsCampaignIdCalendarRoute: AppCampaignsCampaignIdCalendarRoute,
    AppCampaignsCampaignIdTestRenderRoute:
      AppCampaignsCampaignIdTestRenderRoute,
  }

const AppCampaignsCampaignIdRouteWithChildren =
  AppCampaignsCampaignIdRoute._addFileChildren(
    AppCampaignsCampaignIdRouteChildren,
  )

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDataStudioRoute: typeof AppDataStudioRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppYoutubeConnectRoute: typeof AppYoutubeConnectRoute
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRouteWithChildren
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppEditorTemplateIdRoute: typeof AppEditorTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDataStudioRoute: AppDataStudioRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppYoutubeConnectRoute: AppYoutubeConnectRoute,
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRouteWithChildren,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppEditorTemplateIdRoute: AppEditorTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksProcessCampaignQueueRoute:
    ApiPublicHooksProcessCampaignQueueRoute,
  ApiPublicHooksRenderCallbackRoute: ApiPublicHooksRenderCallbackRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
