-- Phase 12 — Organizations, teams, RBAC and workspace isolation.
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  billing_owner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.organization_members (
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('owner','admin','editor','analyst')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended')),
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id,user_id)
);
CREATE TABLE IF NOT EXISTS public.organization_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email text NOT NULL, role text NOT NULL CHECK(role IN ('admin','editor','analyst')), token_hash text NOT NULL UNIQUE,
  invited_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT, expires_at timestamptz NOT NULL,
  accepted_at timestamptz, accepted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS organization_invitations_open_email_uq ON public.organization_invitations(organization_id,lower(email)) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS public.organization_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, action text NOT NULL, target_type text, target_id text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS organization_audit_log_org_created_idx ON public.organization_audit_log(organization_id,created_at DESC);

-- Seed one personal workspace for each existing tenant/user referenced by product data.
INSERT INTO public.organizations(id,name,slug,created_by,billing_owner_user_id)
SELECT gen_random_uuid(), COALESCE(NULLIF(p.full_name,''),split_part(COALESCE(p.email,u.email,'Workspace'),'@',1)) || '''s Workspace',
       'ws-'||replace(u.id::text,'-',''), u.id,u.id
FROM auth.users u LEFT JOIN public.profiles p ON p.id=u.id
ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.organization_members(organization_id,user_id,role)
SELECT o.id,o.created_by,'owner' FROM public.organizations o ON CONFLICT DO NOTHING;

-- Workspace ownership columns. Keep user_id as creator/audit compatibility, but org_id becomes the tenant boundary.
ALTER TABLE public.youtube_connections ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.templates ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.campaigns ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_items ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.automation_logs ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.tenant_capacity_policies ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.tenant_subscriptions ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.billing_customers ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.billing_invoices ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.billing_credit_ledger ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.capacity_usage_events ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.publish_jobs ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;

-- Backfill using each row's existing user owner.
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['youtube_connections','templates','campaigns','campaign_items','assets','automation_logs','tenant_capacity_policies','tenant_subscriptions','billing_customers','billing_invoices','billing_credit_ledger','capacity_usage_events','publish_jobs'] LOOP
    EXECUTE format('UPDATE public.%I x SET organization_id=o.id FROM public.organizations o WHERE x.organization_id IS NULL AND o.created_by=x.user_id',t);
  END LOOP;
END $$;
-- Items/logs can inherit from campaign where historical user ownership was irregular.
UPDATE public.campaign_items ci SET organization_id=c.organization_id FROM public.campaigns c WHERE ci.organization_id IS NULL AND c.id=ci.campaign_id;
UPDATE public.automation_logs l SET organization_id=c.organization_id FROM public.campaigns c WHERE l.organization_id IS NULL AND c.id=l.campaign_id;

CREATE OR REPLACE FUNCTION public.phase12_has_org_role(p_org uuid,p_roles text[] DEFAULT ARRAY['owner','admin','editor','analyst']) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT EXISTS(SELECT 1 FROM public.organization_members m WHERE m.organization_id=p_org AND m.user_id=auth.uid() AND m.status='active' AND m.role=ANY(p_roles));
$$;
CREATE OR REPLACE FUNCTION public.phase12_current_orgs() RETURNS SETOF uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT organization_id FROM public.organization_members WHERE user_id=auth.uid() AND status='active';
$$;
CREATE OR REPLACE FUNCTION public.phase12_default_org(p_user uuid DEFAULT auth.uid()) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT organization_id FROM public.organization_members WHERE user_id=p_user AND status='active' ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END, joined_at LIMIT 1;
$$;
CREATE OR REPLACE FUNCTION public.phase12_audit(p_org uuid,p_action text,p_target_type text DEFAULT NULL,p_target_id text DEFAULT NULL,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN
 IF NOT public.phase12_has_org_role(p_org,ARRAY['owner','admin','editor']) THEN RAISE EXCEPTION 'workspace permission denied'; END IF;
 INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id,metadata_json) VALUES(p_org,auth.uid(),p_action,p_target_type,p_target_id,p_metadata);
END $$;

-- Ensure cross-workspace references can never be attached to a campaign.
CREATE OR REPLACE FUNCTION public.phase12_campaign_integrity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.organization_id IS NULL THEN NEW.organization_id:=public.phase12_default_org(NEW.user_id); END IF;
 IF NEW.youtube_connection_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.youtube_connections y WHERE y.id=NEW.youtube_connection_id AND y.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'YouTube channel belongs to another workspace'; END IF;
 IF NEW.template_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.templates t WHERE t.id=NEW.template_id AND (t.organization_id=NEW.organization_id OR t.is_default=true)) THEN RAISE EXCEPTION 'Template belongs to another workspace'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_phase12_campaign_integrity ON public.campaigns;
CREATE TRIGGER trg_phase12_campaign_integrity BEFORE INSERT OR UPDATE OF organization_id,youtube_connection_id,template_id ON public.campaigns FOR EACH ROW EXECUTE FUNCTION public.phase12_campaign_integrity();
CREATE OR REPLACE FUNCTION public.phase12_item_integrity() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE oid uuid; BEGIN
 SELECT organization_id INTO oid FROM public.campaigns WHERE id=NEW.campaign_id; IF oid IS NULL THEN RAISE EXCEPTION 'campaign not found'; END IF;
 IF NEW.organization_id IS NULL THEN NEW.organization_id:=oid; END IF; IF NEW.organization_id<>oid THEN RAISE EXCEPTION 'campaign item workspace mismatch'; END IF; RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_phase12_item_integrity ON public.campaign_items;
CREATE TRIGGER trg_phase12_item_integrity BEFORE INSERT OR UPDATE OF campaign_id,organization_id ON public.campaign_items FOR EACH ROW EXECUTE FUNCTION public.phase12_item_integrity();

-- Organization/member RLS.
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_invitations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.organization_audit_log ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.organizations,public.organization_members,public.organization_invitations,public.organization_audit_log TO authenticated;
GRANT ALL ON public.organizations,public.organization_members,public.organization_invitations,public.organization_audit_log TO service_role;
DROP POLICY IF EXISTS org_read ON public.organizations; CREATE POLICY org_read ON public.organizations FOR SELECT TO authenticated USING(public.phase12_has_org_role(id));
DROP POLICY IF EXISTS members_read ON public.organization_members; CREATE POLICY members_read ON public.organization_members FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id));
DROP POLICY IF EXISTS invites_read ON public.organization_invitations; CREATE POLICY invites_read ON public.organization_invitations FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));
DROP POLICY IF EXISTS audit_read ON public.organization_audit_log; CREATE POLICY audit_read ON public.organization_audit_log FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','analyst']));

-- Replace direct-user policies for core shared resources.
DROP POLICY IF EXISTS "users select own connections" ON public.youtube_connections; DROP POLICY IF EXISTS "users insert own connections" ON public.youtube_connections; DROP POLICY IF EXISTS "users update own connections" ON public.youtube_connections; DROP POLICY IF EXISTS "users delete own connections" ON public.youtube_connections;
CREATE POLICY yt_org_select ON public.youtube_connections FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id));
CREATE POLICY yt_org_insert ON public.youtube_connections FOR INSERT TO authenticated WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));
CREATE POLICY yt_org_update ON public.youtube_connections FOR UPDATE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin'])) WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));
CREATE POLICY yt_org_delete ON public.youtube_connections FOR DELETE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));

DROP POLICY IF EXISTS "users select own or default templates" ON public.templates; DROP POLICY IF EXISTS "users insert own templates" ON public.templates; DROP POLICY IF EXISTS "users update own templates" ON public.templates; DROP POLICY IF EXISTS "users delete own templates" ON public.templates;
CREATE POLICY templates_org_select ON public.templates FOR SELECT TO authenticated USING(is_default=true OR public.phase12_has_org_role(organization_id));
CREATE POLICY templates_org_insert ON public.templates FOR INSERT TO authenticated WITH CHECK(is_default=false AND public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY templates_org_update ON public.templates FOR UPDATE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor'])) WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY templates_org_delete ON public.templates FOR DELETE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));

DROP POLICY IF EXISTS "users manage own campaigns" ON public.campaigns;
CREATE POLICY campaigns_org_select ON public.campaigns FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id));
CREATE POLICY campaigns_org_insert ON public.campaigns FOR INSERT TO authenticated WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY campaigns_org_update ON public.campaigns FOR UPDATE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor'])) WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY campaigns_org_delete ON public.campaigns FOR DELETE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));

DROP POLICY IF EXISTS "users manage own items" ON public.campaign_items;
CREATE POLICY items_org_select ON public.campaign_items FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id));
CREATE POLICY items_org_insert ON public.campaign_items FOR INSERT TO authenticated WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY items_org_update ON public.campaign_items FOR UPDATE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor'])) WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY items_org_delete ON public.campaign_items FOR DELETE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));

DROP POLICY IF EXISTS "users manage own assets" ON public.assets;
CREATE POLICY assets_org_select ON public.assets FOR SELECT TO authenticated USING(public.phase12_has_org_role(organization_id));
CREATE POLICY assets_org_insert ON public.assets FOR INSERT TO authenticated WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY assets_org_update ON public.assets FOR UPDATE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor'])) WITH CHECK(public.phase12_has_org_role(organization_id,ARRAY['owner','admin','editor']));
CREATE POLICY assets_org_delete ON public.assets FOR DELETE TO authenticated USING(public.phase12_has_org_role(organization_id,ARRAY['owner','admin']));

-- Team management RPCs, all privilege checked and audited.
CREATE OR REPLACE FUNCTION public.phase12_create_invitation(p_org uuid,p_email text,p_role text,p_token_hash text,p_expires_at timestamptz) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE iid uuid; BEGIN
 IF NOT public.phase12_has_org_role(p_org,ARRAY['owner','admin']) THEN RAISE EXCEPTION 'admin permission required'; END IF;
 IF p_role NOT IN ('admin','editor','analyst') THEN RAISE EXCEPTION 'invalid role'; END IF;
 INSERT INTO public.organization_invitations(organization_id,email,role,token_hash,invited_by,expires_at) VALUES(p_org,lower(p_email),p_role,p_token_hash,auth.uid(),p_expires_at) RETURNING id INTO iid;
 INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id,metadata_json) VALUES(p_org,auth.uid(),'member.invited','invitation',iid::text,jsonb_build_object('email',lower(p_email),'role',p_role)); RETURN iid;
END $$;
CREATE OR REPLACE FUNCTION public.phase12_accept_invitation(p_token_hash text,p_user_email text) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE i public.organization_invitations%ROWTYPE; BEGIN
 SELECT * INTO i FROM public.organization_invitations WHERE token_hash=p_token_hash AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at>now() FOR UPDATE;
 IF i.id IS NULL OR lower(i.email)<>lower(p_user_email) THEN RAISE EXCEPTION 'invalid invitation'; END IF;
 INSERT INTO public.organization_members(organization_id,user_id,role) VALUES(i.organization_id,auth.uid(),i.role) ON CONFLICT(organization_id,user_id) DO UPDATE SET role=EXCLUDED.role,status='active';
 UPDATE public.organization_invitations SET accepted_at=now(),accepted_by=auth.uid() WHERE id=i.id;
 INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id,metadata_json) VALUES(i.organization_id,auth.uid(),'member.joined','user',auth.uid()::text,jsonb_build_object('role',i.role)); RETURN i.organization_id;
END $$;
CREATE OR REPLACE FUNCTION public.phase12_set_member_role(p_org uuid,p_user uuid,p_role text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN
 IF NOT public.phase12_has_org_role(p_org,ARRAY['owner','admin']) THEN RAISE EXCEPTION 'admin permission required'; END IF;
 IF p_role NOT IN ('admin','editor','analyst') THEN RAISE EXCEPTION 'owner role transfer requires explicit ownership transfer'; END IF;
 IF EXISTS(SELECT 1 FROM public.organization_members WHERE organization_id=p_org AND user_id=p_user AND role='owner') THEN RAISE EXCEPTION 'cannot modify owner role'; END IF;
 UPDATE public.organization_members SET role=p_role WHERE organization_id=p_org AND user_id=p_user;
 INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id,metadata_json) VALUES(p_org,auth.uid(),'member.role_changed','user',p_user::text,jsonb_build_object('role',p_role));
END $$;
CREATE OR REPLACE FUNCTION public.phase12_remove_member(p_org uuid,p_user uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN
 IF NOT public.phase12_has_org_role(p_org,ARRAY['owner','admin']) THEN RAISE EXCEPTION 'admin permission required'; END IF;
 IF EXISTS(SELECT 1 FROM public.organization_members WHERE organization_id=p_org AND user_id=p_user AND role='owner') THEN RAISE EXCEPTION 'cannot remove workspace owner'; END IF;
 DELETE FROM public.organization_members WHERE organization_id=p_org AND user_id=p_user;
 INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id) VALUES(p_org,auth.uid(),'member.removed','user',p_user::text);
END $$;

-- Organization billing/capacity helper: billing owner remains provider identity, quotas are workspace-owned.
CREATE UNIQUE INDEX IF NOT EXISTS tenant_capacity_policies_org_uq ON public.tenant_capacity_policies(organization_id) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS tenant_subscriptions_org_uq ON public.tenant_subscriptions(organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS campaigns_org_idx ON public.campaigns(organization_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS assets_org_idx ON public.assets(organization_id,created_at DESC);
CREATE INDEX IF NOT EXISTS youtube_connections_org_idx ON public.youtube_connections(organization_id,created_at DESC);

REVOKE ALL ON FUNCTION public.phase12_create_invitation(uuid,text,text,text,timestamptz), public.phase12_accept_invitation(text,text), public.phase12_set_member_role(uuid,uuid,text), public.phase12_remove_member(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.phase12_create_invitation(uuid,text,text,text,timestamptz), public.phase12_accept_invitation(text,text), public.phase12_set_member_role(uuid,uuid,text), public.phase12_remove_member(uuid,uuid) TO authenticated;
CREATE OR REPLACE FUNCTION public.phase12_default_org_trigger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.organization_id IS NULL THEN NEW.organization_id:=public.phase12_default_org(NEW.user_id); END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_phase12_youtube_default_org ON public.youtube_connections; CREATE TRIGGER trg_phase12_youtube_default_org BEFORE INSERT ON public.youtube_connections FOR EACH ROW EXECUTE FUNCTION public.phase12_default_org_trigger();
DROP TRIGGER IF EXISTS trg_phase12_templates_default_org ON public.templates; CREATE TRIGGER trg_phase12_templates_default_org BEFORE INSERT ON public.templates FOR EACH ROW EXECUTE FUNCTION public.phase12_default_org_trigger();
DROP TRIGGER IF EXISTS trg_phase12_assets_default_org ON public.assets; CREATE TRIGGER trg_phase12_assets_default_org BEFORE INSERT ON public.assets FOR EACH ROW EXECUTE FUNCTION public.phase12_default_org_trigger();

-- Organization-scoped billing/quota view: the billing owner is the financial identity; all members consume the same policy/fairness tenant ID.
CREATE OR REPLACE FUNCTION public.phase12_org_entitlement(p_org uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE o public.organizations%ROWTYPE; e jsonb; p jsonb; BEGIN
 SELECT * INTO o FROM public.organizations WHERE id=p_org; IF NOT FOUND THEN RAISE EXCEPTION 'workspace not found'; END IF;
 e:=public.phase11_effective_plan(o.billing_owner_user_id); p:=public.phase10_policy(o.billing_owner_user_id);
 RETURN jsonb_build_object('organizationId',p_org,'billingOwnerUserId',o.billing_owner_user_id,'entitlement',e,'policy',p);
END $$;
REVOKE ALL ON FUNCTION public.phase12_org_entitlement(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.phase12_org_entitlement(uuid) TO service_role;
CREATE OR REPLACE FUNCTION public.phase12_resource_audit_trigger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE oid uuid; tid text; BEGIN
 oid:=COALESCE(NEW.organization_id,OLD.organization_id); tid:=COALESCE(NEW.id,OLD.id)::text;
 IF oid IS NOT NULL THEN INSERT INTO public.organization_audit_log(organization_id,actor_user_id,action,target_type,target_id,metadata_json)
 VALUES(oid,auth.uid(),lower(TG_TABLE_NAME)||'.'||lower(TG_OP),TG_TABLE_NAME,tid,jsonb_build_object('operation',TG_OP)); END IF;
 RETURN COALESCE(NEW,OLD);
END $$;
DROP TRIGGER IF EXISTS trg_phase12_audit_campaigns ON public.campaigns; CREATE TRIGGER trg_phase12_audit_campaigns AFTER INSERT OR UPDATE OR DELETE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION public.phase12_resource_audit_trigger();
DROP TRIGGER IF EXISTS trg_phase12_audit_templates ON public.templates; CREATE TRIGGER trg_phase12_audit_templates AFTER INSERT OR UPDATE OR DELETE ON public.templates FOR EACH ROW EXECUTE FUNCTION public.phase12_resource_audit_trigger();
DROP TRIGGER IF EXISTS trg_phase12_audit_assets ON public.assets; CREATE TRIGGER trg_phase12_audit_assets AFTER INSERT OR UPDATE OR DELETE ON public.assets FOR EACH ROW EXECUTE FUNCTION public.phase12_resource_audit_trigger();
DROP TRIGGER IF EXISTS trg_phase12_audit_youtube ON public.youtube_connections; CREATE TRIGGER trg_phase12_audit_youtube AFTER INSERT OR UPDATE OR DELETE ON public.youtube_connections FOR EACH ROW EXECUTE FUNCTION public.phase12_resource_audit_trigger();
